package pack.restserver;

/**
 * Created by administrator on 21.06.16.
 */
public class eye_colortemp {

    public static String[] eye_color = new String[]{
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Hazel" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Hazel" ,
            "Blue" ,
            " " ,
            "Hazel,Brown" ,
            " " ,
            "Hazel" ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Brown" ,
            "Green,Brown,Black" ,
            " " ,
            "Green" ,
            "Pink,Teal,Green,Orange,Neutral" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            " " ,
            " " ,
            "Green,Brown" ,
            "Black" ,
            " " ,
            " " ,
            "Green" ,
            "Blue" ,
            " " ,
            "Hazel" ,
            "Teal,Yellow,Neutral,Copper,Brown,Black" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            "Brown" ,
            "Brown" ,
            " " ,
            " " ,
            "Yellow,Neutral,Copper,Brown,Black" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Blue,Neutral,Copper,Brown,Black" ,
            "Hazel" ,
            "Blue" ,
            " " ,
            "Orange,Neutral,Brown,Black" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            " " ,
            "Purple,Blue,Neutral,Black" ,
            "Teal,Neutral,Black" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Purple,Teal,Green,Gray" ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Green" ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Hazel" ,
            "Blue,Neutral,Brown" ,
            "Brown" ,
            "Black" ,
            "Brown" ,
            "Blue" ,
            " " ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Hazel" ,
            " " ,
            " " ,
            "Blue,Orange,Red,Neutral,Black" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            " " ,
            "Orange,Neutral,Copper,Black" ,
            "Brown" ,
            "Green" ,
            " " ,
            " " ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            " " ,
            " " ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green,Yellow,Orange,Neutral,Black" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Purple,Blue,Neutral,Black" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Purple,Blue,Green,Neutral,Brown" ,
            " " ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            " " ,
            " " ,
            "Copper,Brown" ,
            " " ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Hazel" ,
            "Green" ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            "Green" ,
            " " ,
            "Hazel" ,
            "Green" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Hazel" ,
            "Brown" ,
            " " ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Purple,Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Red" ,
            "Green" ,
            "Black" ,
            "Green" ,
            "Hazel" ,
            "Green" ,
            " " ,
            "Blue" ,
            " " ,
            "Blue" ,
            " " ,
            "Hazel" ,
            "Purple,Neutral,Copper,Black" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            " " ,
            " " ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            " " ,
            " " ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Green" ,
            " " ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Black" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Brown" ,
            "Green" ,
            " " ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Hazel" ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            "Green" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue,Neutral,Black" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Yellow,Orange,Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Hazel" ,
            "Green" ,
            "Neutral,Copper,Brown,Black" ,
            "Green" ,
            "Green" ,
            "Green" ,
            " " ,
            "Hazel" ,
            " " ,
            "Hazel" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Brown" ,
            "Green" ,
            " " ,
            " " ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            " " ,
            "Green" ,
            " " ,
            "Green" ,
            " " ,
            " " ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            " " ,
            " " ,
            "Hazel" ,
            "Brown" ,
            "Hazel" ,
            "Black" ,
            "Brown" ,
            "Blue" ,
            " " ,
            " " ,
            "Green" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            "Neutral,Copper,Brown,Black" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Hazel" ,
            "Gray" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            " " ,
            " " ,
            "Brown" ,
            "Brown" ,
            " " ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            " " ,
            "Brown" ,
            " " ,
            "Teal,Green,Black" ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Black" ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Green" ,
            " " ,
            "Green" ,
            "Hazel" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Hazel" ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            " " ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Yellow,Copper,Brown,Black" ,
            " " ,
            "Hazel" ,
            "Blue" ,
            " " ,
            "Blue" ,
            "Neutral,Black" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            " " ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Hazel" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Teal,Yellow,Black" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            "Brown" ,
            " " ,
            "Black" ,
            "Blue" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Gray" ,
            "Blue" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Blue" ,
            " " ,
            "Hazel" ,
            "Paolla MakeUp" ,
            " " ,
            "Black" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Gray" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Gray" ,
            "Brown" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            " " ,
            "Brown" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green,Yellow,Black" ,
            "Green" ,
            "Orange,Brown,Black" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Gray" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            " " ,
            "Green" ,
            " " ,
            "Pink,Orange,Black" ,
            " " ,
            "Blue" ,
            " " ,
            "Brown" ,
            " " ,
            " " ,
            "Green" ,
            "Blue" ,
            " " ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Teal,Gray,Black" ,
            "Blue,Red,Neutral" ,
            "Black" ,
            "Brown" ,
            "Blue" ,
            "Purple,Blue,Green,Yellow,Black" ,
            "Green" ,
            " " ,
            "Gray" ,
            "Brown" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Hazel" ,
            " " ,
            " " ,
            "Black" ,
            "Blue" ,
            "Black" ,
            "Green" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Hazel" ,
            "Hazel" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Black" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Green" ,
            " " ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Hazel" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            " " ,
            "Blue" ,
            " " ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            "Purple,Neutral,Copper,Brown" ,
            "Green" ,
            "Pink,Purple,Orange,Neutral,Black" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            " " ,
            " " ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Brown" ,
            "Hazel" ,
            "Hazel" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Black" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Gray" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Gray" ,
            "Gray" ,
            "Black" ,
            "Blue" ,
            "Blue" ,
            "Blue,Green,Yellow,Orange,Copper" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Hazel" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Teal,Orange,Neutral,Copper,Brown,Black" ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Purple,Neutral,Copper" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Brown" ,
            "Green,Yellow,Brown,Black" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Gray" ,
            "Blue" ,
            "Brown" ,
            "Gray" ,
            " " ,
            "Red,Black" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Hazel" ,
            "Brown" ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Gray" ,
            "Hazel" ,
            "Blue" ,
            "Pink,Purple,Orange" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Pink,Purple,Orange,Neutral,Black" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Purple,Blue,Neutral,Black" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Yellow,Copper,Brown" ,
            "Gray" ,
            "Brown" ,
            "Blue" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            " " ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            " " ,
            "Green" ,
            "Green" ,
            " " ,
            "Blue" ,
            "Gray" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Yellow,Orange,Neutral,Black" ,
            "Brown" ,
            "Blue" ,
            "Hazel" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Gray" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Black" ,
            "Blue" ,
            "Purple,Neutral,Copper" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Hazel" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Pink,Purple,Neutral" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Purple,Blue,Orange,Copper,Black" ,
            "Copper,Brown" ,
            "Pink,Blue,Yellow,Black" ,
            "Blue" ,
            "Pink,Copper,Black" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Teal,Red,Brown" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Hazel" ,
            "Brown" ,
            "Blue" ,
            " " ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Gray" ,
            "Brown" ,
            "Gray" ,
            "Brown" ,
            "Brown" ,
            "Gray" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            "Hazel" ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Black" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Alieneczka" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Purple,Blue" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Black" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Brown" ,
            "Yellow,Orange,Red" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Hazel" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            " " ,
            "Hazel" ,
            " " ,
            "Hazel" ,
            "Green" ,
            "Hazel" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Hazel" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Gray" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Hazel" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Orange,Brown" ,
            "Brown" ,
            "Hazel" ,
            "Green" ,
            "Hazel" ,
            "Black" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue,Yellow,Black" ,
            "Blue" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Gray" ,
            "Brown" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Green" ,
            "Purple,Green" ,
            "Hazel" ,
            "Brown" ,
            " " ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Green" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Hazel" ,
            "Blue" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Gray" ,
            "Green" ,
            "Brown" ,
            "Brown" ,
            "Purple,Yellow" ,
            "Brown" ,
            "Green" ,
            "Blue" ,
            "Hazel" ,
            "Gray" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            " " ,
            " " ,
            "Hazel" ,
            " " ,
            " " ,
            "Purple,Black" ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            " " ,
            "Blue" ,
            "Brown" ,
            "Brown" ,
            "Green" ,
            "Gray" ,
            " " ,
            "Brown" ,
            "Brown" ,
            " " ,
            "Brown" ,
            "Hazel" ,
            "Green" ,
            "Green" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Black" ,
            "Hazel" ,
            "Brown" ,
            "Blue" ,
            "Green" ,
            "Blue" ,
            "Green" ,
            "Hazel" ,
            "Green" ,
            "Hazel"
    };
}
