package pack.restserver;

/**
 * Created by administrator on 21.06.16.
 */
public class occasionstemp {

    public static String[] occasions = new String[]{
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired, Holiday Inspired, Everyday, Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Celebrity Inspired, Dramatic, Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            " " ,
            "Everyday" ,
            " " ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Black" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Brown" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Blue" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Blue" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Hazel" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Blue" ,
            "Blue" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Hazel" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Hazel" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Blue" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Green" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Brown" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Green" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            " " ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Green" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Brown" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            " " ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Gray" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            " " ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            " " ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Hazel" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Green" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            " " ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Green" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Purple,Neutral,Black" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Green" ,
            "Dramatic" ,
            "Green" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Brown" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic, Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Green" ,
            "Hazel" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Blue" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Blue" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Blue" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Green" ,
            "Everyday" ,
            "Hazel" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Brown" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Green" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Blue" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Blue" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Green" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Green" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Blue" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Blue" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Blue" ,
            "Blue" ,
            "Blue" ,
            "Everyday" ,
            "Green" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Blue" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            " " ,
            "Everyday" ,
            "Pink,Purple,Teal,Neutral" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            " " ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            " " ,
            "Dramatic" ,
            "Blue" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Brown" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            " " ,
            "Dramatic, Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            " " ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            " " ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Brown" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Green" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Green" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Brown" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Celebrity Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            " " ,
            "Dramatic" ,
            "Everyday" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Everyday" ,
            " " ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Dramatic" ,
            "Dramatic" ,
            "Everyday" ,
            "Dramatic" ,
            "Holiday Inspired" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Everyday" ,
            "Holiday Inspired" ,
            "Holiday Inspired" ,
            "Celebrity Inspired" ,
            "Celebrity Inspired" ,
            "Dramatic"
    };
}
