package pack.restserver;

/**
 * Created by administrator on 21.06.16.
 */
public class titlestemp {

    public static String[] titles = new String[]{
            "Urban Decay Ammo palette look: Brown",
            "Smokey browns",
            "Inverse Gradient: Teal, Gold & Brown Eyes",
            "Teal and Purple!",
            "Antique MAC pigment look",
            "fantastic",
            "neutral",
            "Oranges and plums",
            "Natural cut crease",
            "Rock Chick",
            "Pretty in Pink:  Breast Cancer Look",
            "valentines",
            "Tamed Orange",
            "A look with MUG shadows",
            "Burning Eyes",
            "Red hot Valentine's day makeup with MUG eyeshadows",
            "Sensuous purple and gold",
            "Minnie mouse",
            "Glitter Claw :)",
            "Blushing Eyes",
            "Neutral cut crease",
            "Raspberry Margaritas",
            "Neutral Smokey Eye",
            "Dark & sparkly MAC look",
            "Sleek Respect #2",
            "Golden Rose Eyes - Great for St. Patrick's Day Makeup & Christmas Makeup",
            "Golden Girl",
            "Jangsarasque",
            "Fall-Inspired Ben Nye look",
            "Classical look",
            "Blue Smokey",
            "Ombre Liner",
            "New Years Eve Makeup (Kim Kardashian Vegas Shoot look )",
            "MAC Look: Deep Purple/Polished Ivory/Push the Edge",
            "for a date.",
            "Idea Gallery: Photo Tutorials",
            "Get Naked with Too Faced",
            "Idea Gallery: Video Tutorials",
            "Peacock",
            "Forest smoke",
            "Brown but not boring",
            "simple everyday look",
            "Acid Sunset",
            "Shimmery Gold",
            "The Princess and the Frog",
            "mango tango.",
            "makeup",
            "Jessica Alba Inspired",
            "colour pop",
            "Zombie Witch",
            "Carribean accent",
            "brocaded",
            "Neutral shimmery eyes &#038",
            "Colorful Arab Eye With MUFE",
            "Darkened Gold Gal",
            "Sensuous",
            "Pink",
            "Purple/navy smokey",
            "Glamorous",
            "MUG Neutrals!",
            "Gorgeous Gunmetal Eyes",
            "Colorful Mardi Gras Eyes",
            "Garden of Good and Evil",
            "End Of Summer",
            "Outrageously Colorful Cabaret Eyes",
            "Cat Eye",
            "Golden brown with MUG eyeshadows",
            "Purple and Coral",
            "lace eye",
            "Gold Grape",
            "soft pink Valentine's Day look",
            "Neutral glam",
            "classic",
            "Nude Purple Smoky eye",
            "SUNNY",
            "color full",
            "Brown Sugar",
            "Chestnuts Roasting",
            "Good Vibes",
            "Wedding make up",
            "Colours of Autumn",
            "little blue dragon art makeup",
            "Purple rain",
            "The Mad Hatter's Asylum",
            "Portrait Ready",
            "Pocahontas inpired",
            "Afterglow",
            "Shay Mitchell -  makeup inspired",
            "Dragon scales",
            "Naked 2 Evening Look",
            "Simple Brown&#038",
            "lovely",
            "Inverted Sodalite Blue Smokey Eye",
            "My Versace Haute Couture 2012 inspired make up",
            "Frozen eyes",
            "Colorful Summer!",
            "Kenia Inspired",
            "Brown",
            "Romantic Gold &#038",
            "Let's Tango",
            "Pink and Blue",
            "Golden Sunrise",
            "Juicy pastels",
            "birthday wish",
            "Opposit of the winter",
            "classic rock",
            "Autumn Inspired",
            "Violet Love",
            "Clean Edges",
            "Glammy Goes To&#8230",
            "Blue",
            "A Little Bit of Warmth",
            "fresh oranges",
            "Au naturale",
            "Daily make-up",
            "Fall trends",
            "Autumn nights",
            "Autumn Sunset",
            "Fashion Inspired",
            "Victoria's Secret revealed",
            "Blue&#038",
            "Dark",
            "Wedding make up",
            "Golden summer",
            "Orange &#038",
            "Inspired by the dragon from Enchanted",
            "Sweet pink",
            "breath",
            "Enchanted",
            "Green",
            "Appletini :)",
            "Blue Lagoon",
            "Lace eyes",
            "Mad Bee",
            "Bright and Lovely",
            "Bluesy Neutrals",
            "emerald cateye",
            "INSOMNIA.",
            "Prince Charming",
            "Autumn Sky",
            "Over the mountains",
            "Spot light eye",
            "Dark NYX look with Cryptonite",
            "Blue Glitter &#038",
            "White&#038",
            "autumn look",
            "Teal and grey",
            "Bloody zombie",
            "Electric Purple",
            "smoky heather",
            "Mermaid",
            "Extreme Cateye",
            "Glitter Eye",
            "rainbow",
            "Fineness",
            "Emerald smoky",
            "purple &#038",
            "Chartruese Infustion - A MAC Dupe Look inspired by Tiffany D",
            "Green sparkle",
            "Corpse Bride",
            "Glowing for Fall",
            "naked",
            "Daisy",
            "MUG sunrise",
            "Sex on Fire",
            "black gold",
            "turquoise with brown.",
            "Soft violet",
            "blue eye",
            "Bitten Utopia",
            "Nude &#038",
            "Simply look",
            "Partyyy",
            "Galaxy",
            "Daily make-up",
            "Monster High series: Laguna Blue",
            "Leather-Studded Makeup",
            "Lime me up!",
            "party green",
            "Taupe",
            "Eye Candy",
            "Lemonade",
            "Sexy Smokey with MAC and MUFE",
            "Smashbox Soft Box Look",
            "Red&#038",
            "Pink, Blue&#038;Purple",
            "Copper",
            "Chocolate Make Up",
            "Mix",
            "Tropical Dream",
            "Beyonce 'mine' inspired.",
            "Sugar Skull",
            "Harley Quinn",
            "Peach&#038",
            "Mango",
            "Ballroom blitz",
            "Chickadee :)",
            "Deathrocker",
            "Brown Lilly",
            "Red Glitter",
            "Cheshire cat inspired :D",
            "Monaco",
            "valentines 2",
            "Nicole Scherzinger Inspired",
            "Sky Blue liner",
            "Colourful Arabic eye :)",
            "Emerald With a Pop",
            "cornflower, grass and sunset",
            "Beyonce - Countdown",
            "Duochrome Smoke",
            "Dramatic Blue",
            "Poison Berry",
            "Lollipop",
            "makeup",
            "Bora Bora Inspired",
            "October",
            "Purple Makeup",
            "Electric",
            "Colourful South Asian / Arabic inspired bridal makeup",
            "Burlesque tango",
            "purple",
            "Colorful",
            "Sexy, smokey Utopia!",
            "Glitter Eyeliner",
            "Gold &#038",
            "Flirtatious Birthday",
            "oriental princess",
            "Two-colour makeup",
            "Pop of Glitter",
            "Autumn Spirit",
            "Razzleberry",
            "Yellow Wawe",
            "Emma Stone inspired (MTV Music Video Awards 2012)",
            "Midnight Blue",
            "glistening gold",
            "Purple &#038",
            "Satellite on Peacock",
            "smoky with a touch of pink",
            "haute chocolate",
            "Green&#038",
            "Sensuous",
            "ENVY me",
            "Colorful Gasoline with Sugarpill",
            "Red shadow",
            "Look 4 from Metal Chicks series - Marilyn Manson",
            "Chocolate and caramel.",
            "Bright Envy",
            "Electric Purple",
            "utopia lights",
            "Candy Galaxy",
            "Green makeup",
            "Sweet Lilly",
            "A drop of Liquid Gold",
            "Turquoise sparkle",
            "Cosmic sunset",
            "Spring Purples",
            "Brown &#038",
            "Sugar Bow :)",
            "seaside sunset",
            "Elegant brown",
            "clasics 2",
            "art",
            "Black and white cut crease",
            "New Years Party Makeup for Kids and Teens by Emma",
            "MAC Pigment look: Peacock",
            "Purple haze",
            "Frosty forest",
            "Neon Makeup",
            "Green",
            "Green line",
            "colourful eye",
            "'Touch of Electric Blue' Look",
            "Peacock's eye",
            "..::: ..Smokey..E. :::..",
            "Enchanted",
            "Sparkle / dramatic for prom",
            "Golden sand",
            "Poison Smokey",
            "Shimmering Autumn",
            "Beauty Makeup",
            "Ocean Breeze :)",
            ":)",
            "colorfull",
            "Peacock's Love",
            "Rosy lips",
            "Minty Brown",
            "bluetiful",
            "Dramatic",
            "Brown",
            "Turquoise",
            "Cut crease",
            "Matte lips",
            "Touch of violet",
            "Colorful Arabic eye with MAC pigments",
            "Pink eye lol",
            "Sweet Dreams",
            "Poison green",
            "Tropical HoliDAZE",
            "neon green &#038",
            "Classic with a touch of cobalt",
            "Exotic look",
            "Spring on the rock",
            "Jogurtowy",
            "Smoked out plum liner",
            "Showgirl",
            "Explosion of Colour!",
            "Sweet Razzleberry",
            "glitter mask",
            "Fantasy Makeup",
            "Golden Pink",
            "makeup",
            "back to black.",
            "Electric Combination",
            "Beautiful Burlesque",
            "SPRING",
            "Spring inspired",
            "Sundowner",
            "Purple and green craziness!",
            "Fallen Leaves",
            "Dark Dandelions: Emerald Smokey Eye with Colorful Metallic Accent",
            "Spring",
            "White &#038",
            "Winged Eyeliner Tutorial",
            "Make up",
            "Burning Autumn",
            "Utopia",
            "I like it",
            "Cotton Candy!",
            "Violet glitter.",
            "Into the light",
            "Power of violet",
            "Blue vs. Hazel",
            "Happy Valentine's Day!",
            "Good Night&#8230",
            "Artistic",
            "makeup",
            "Sin",
            "Makeup Glam",
            "Rainbow Lips Tutorial",
            "Shiny Blue",
            "siren",
            "Shimmermint",
            "Granny Smith Apple Look",
            "Wet 'n' Wild Neutral Look",
            "Chocolate in mint :)",
            "!@#$%^",
            "The City of Lost Children inspired",
            "Nightlife",
            "Crystal shade",
            "New Year's Eve Night",
            "Autumnal Eyes",
            "MAC Viva Glam Gaga 2 look",
            "Extreme 60's inspired look with NYX",
            "Bittenly True",
            "Magic",
            "Glitter on New Year's Eve",
            "Green Lantern *Inspired*",
            "Champagne Glitz, New Years Eve look",
            "Half Baked",
            "Egypt Inspired",
            "Purple smokey",
            "Kiss the rainbow",
            "every Day",
            "It's for paparazzi, it's for fame!",
            "Cybergoth blues",
            "Makeup - Scarf",
            "Dream country",
            "Marry",
            "Cut Crease Diamond",
            "utopia #2",
            "Basic",
            "So Sweet",
            "Urban Decay Ammo palette look: Green and brown",
            "Intense Valentine",
            "Utopia",
            "Green",
            "Burning Night Sky",
            "Gold makeup",
            "Raspberries with gold",
            "Gel Liners",
            "Copper autumn",
            "Smoldering Purple With White Gold",
            "Summer Eyes Tutorial",
            "blackest black",
            "everyday gold.",
            "Mojito STYLE",
            "last christmas.",
            "GRAPHIC eye",
            "Club Makeup",
            "New Years Eve Purple",
            "Ben Nye look: Pink, Purple and Peach",
            "Aquamarine",
            "Makeup - Angelina Jolie",
            "A'la Dita Von Teese",
            "Lazuli",
            "Taunting Teal",
            "Indigo",
            "Nicki Minaj Beez In The Trap Inspired Makeup",
            "Winter - GO AWAY!!!",
            "One of my favorite looks . (not done by me)",
            "Blue Chaos",
            "Everyday neutral",
            "Peacock inspired with MAC pigments",
            "Inspired by Fall",
            "Flower Dreams :)",
            "makeup",
            "120 Palette: Violet Rose's Indian Sunset",
            "Keeping it classy with Naked 2",
            "Summer pin up Girl",
            "Face chart INSPIRED :)",
            "Lion",
            "Girl with the dragon tattoo",
            "Pink and orange style",
            "St Patrick's Day Eye Makeup",
            "Sparkle",
            "Birthday Wish",
            "Women in black",
            "Arabic Inspired Makeup look",
            "White&#038",
            "Colorful Eye Makeup",
            "Turquoise",
            "The Beast",
            "strong liner.",
            "Gold &#038",
            "sparkling green",
            "Maroon lips",
            "Viola",
            "Friday morning",
            "Gold dust smoky",
            "My utopia",
            "I've Got the Golden Ticket!",
            "Natural Smokey Eye",
            "Purple Rain",
            "Coffee &#038",
            "Cat",
            "Fantasy",
            "Utopia",
            "Natural with dark crease",
            ":)",
            "Bronzed Eye",
            "Extreme Smoky for Blue Eyes",
            "Sexy Blues",
            "Makeup - Agnieszka Popielewicz",
            "Soft brown brightening makeup finish",
            "Rainbow",
            "smokey eye purple",
            "Pixie Dust",
            "new years #2",
            "Pinkalicious",
            "shades of pink and purple",
            "Some spring into the winter",
            "Wanna some chocolate?",
            "Neon Summer",
            "Cocoa Bear!",
            "Kim Kardashian Inspired Purple Smokey Eye",
            "makeup",
            "Colorful",
            "Blue flower",
            "Face chart INSPIRED :) Orange and blue :)",
            "Prom in Glitter! :)",
            "Golden Liner",
            "Full of Envy",
            "Graphic Halloween",
            "Pretty Pastel",
            "Gray Tartan",
            "GOLD Christmas",
            "burlesque",
            "Spicy Lime",
            "pink",
            "dawn line",
            "My go-to look",
            "St. Patrick's Day Look",
            "Sweet Valentine's Day Look",
            "Lady Raven",
            "Mermaid Vibes",
            "Night Of Cairo",
            "MAC Look: Bloodline &#038",
            "Burning Love Smokey",
            "Grey Smoky",
            "JackTown Orange",
            "Green gradient",
            "Summer Evening",
            "Daily makeup",
            "Lovely Corals :)",
            "Touch of Burgundy",
            "Rose Gold Smokey",
            "Eva Longoria Cannes 2013 - Makeup Look",
            "Makeup - Christina Aguilera - Moves like Jagger",
            "Barely Natural",
            "Monster House",
            "Green with Envy",
            "Sexy Vamp",
            "Neon Inferno",
            "MAC Look: Pagan/Kelly Green/Chartreuse",
            "Brown &#038",
            "Insomnia",
            "Tropical glam.",
            "Summer Rain",
            "Miss Autumn",
            ":)",
            "Daily smokey",
            "Dreamy night",
            "Burn the witch",
            "Something New",
            "Colourful",
            "Simple Sunkissed Eyes for your Inner Golden Goddess",
            "Golden Bear",
            "I'm a Gold Digger",
            "BLACK GREEN",
            "Brown Diablo",
            "I Love Getting UD NAKED!",
            "Test",
            "C'mon Chameleon",
            "Tropical Flower",
            "Autumn Tales",
            "Chronic Berry",
            "Fresh Everyday Glam",
            "Setting Sun",
            "Pumpkin Spice",
            "Unicorn Eggs! :)",
            "Homecoming Goddes",
            "spot light",
            "My everyday look",
            "Eyes-nails matchy matchy",
            "Navy Blue",
            "summer harmony",
            "New Years Eve Pigment",
            "smoky with duochrome",
            "Browns and blue accent",
            "multicolor",
            "Smokey - total black!",
            "tropics",
            "Vamp makeup",
            "Springly!",
            "Sea mist &#038",
            "glitter eye",
            "Lime Green and Bright Blue look for spring!",
            "Autumn Smoky Eyes",
            "Out Of Coffin",
            "Sun Cocktail",
            "Alice in Wonderland Palette Look",
            "Neon accent",
            "Tropical fiver",
            "Alien",
            "Inspired by Belle from Beauty and the Beast",
            "Sexy Vamp/Gothic makeup for Halloween",
            "Across the sea",
            "blink blink",
            "Jewel Bug",
            "Luck of the Irish",
            "Mermaid Lagoon :)",
            "Blue and Coral",
            "MAC Hilary Duff (take 1)",
            "Nightlife look",
            "Vintage romance",
            "natural look",
            "Purple Rain",
            "Warm, sweet look with gold",
            "Sexy Glitter",
            "Classic Wedding Make Up",
            "rockabilly",
            "Untitled_8",
            "Summer",
            "NYE Glitter Bomb",
            "neutral with pop of purple",
            "Cat Eye",
            "spring around",
            "Red-winged Blackbird",
            "Cute bow",
            "Golden Glow",
            "makeup in shades of gray",
            "chameleon",
            "colorful",
            "colorful make-up",
            "Bohemian",
            "Neon colored line",
            "White Leopard - With a touch of red :)",
            "Parfait divine",
            "Purple Smokey",
            "Kristen Stewart Makeup Look MUG shadows",
            "Pink champagne",
            "Birthday Wish!",
            "My Alter Ego: Barbie",
            "First love",
            "Fire Outside",
            "sugar skull",
            "dream of eden",
            "Caribbean sun",
            "Navy peacock",
            "Summer 2",
            "Burgundy Orchid with Gold",
            "Glazel",
            "Red and white",
            "COOKIE MONSTER OM NOM NOM",
            "Sweet Valentine",
            "Sleek Sparkle 2 Eyeshadow Palette - MakeUp",
            "rainbow",
            "Waves at Sea",
            "Pink and blue mystery",
            "2 am heartbreak",
            "Mermaid Eye",
            "Blue sky",
            "Deep burgundy",
            "Inspiration beer Redd's",
            "Frankenstein's girlfriend",
            "Color Geek",
            "Colourful Smokey Eyes",
            "Pixie Sparkle",
            "Classic Smoky",
            "Colorful",
            "Bronze Goddess",
            "Utopia&#038",
            "Electric Teal",
            "Green",
            "Summertime Lagoon",
            "Purple glittery eyeliner",
            "Psycho Killer Clown",
            "Black&#038",
            "Gold and Brown Cut Crease",
            "Face chart CHALLENGE :)",
            "? color eye",
            "wine and snow white",
            "Mandarine",
            "Exotic Glamour",
            "Make a wish",
            "Expensive Pink",
            "Pretty Plum",
            "Chrysanthemum",
            "gold",
            "Easter Candy Eggs :)",
            "Rainbow",
            "Katy Perry's SMURF",
            "Aubergine Dream",
            "Sparklin' cateye",
            "Pigments",
            "Neutral smokey with utopia",
            "Sea Mist",
            "Spicy Wine",
            "Birthday Wish",
            "Natural look",
            "Technic",
            "Still got the blue(s)",
            "Color me now :)",
            "Copper Olive",
            "Green Fairy",
            "Foxy",
            "Blue hot sky",
            "Neon yellow with blue pearl",
            "Glittery Cat Eye",
            "magnetizing green&#038",
            "Ocean Breeze",
            "Fireworks",
            "Gemini",
            "Chocolate glitter",
            "Arsenic",
            "I need some water",
            "Arabian Adventure",
            "Chic",
            "Phoenix Inspired Look!",
            "Night Clubbing",
            "Pink and Blue",
            "Fierce MUG",
            "Black&#038",
            "Pink",
            "Insomnia nights",
            "My Go to Smokey Eye",
            "Sugar Skull",
            "Sky on Fire",
            "Graphic Rainbow Eye Makeup Look",
            "Summer Lovin :)",
            "Fall Makeup",
            "Giggly Mango",
            "whispie sweet nothings",
            "pop of color",
            "MannyMuaxMakeupGeek #1",
            "Pegasus",
            "mint in violet",
            "Arabic makeup :-)",
            "The main role Utopia",
            "line is the basis",
            "Spring Lavender",
            "Lime",
            "sensual bridal make up",
            "Delete",
            "Peach and Aqua",
            "colorful bird",
            "Algae",
            "Carnival Make-up",
            "NEON",
            "Lagoon",
            "Pastel look",
            "Hollywood Lust",
            "iridescent green",
            "mermaid splash",
            "Jennifer Lopez Oscars 2012 Look",
            "Modern Cleopatra",
            "Superbowl Look!",
            "Teal & Brown for Hazel Eyes",
            "Greed",
            "Starry Night",
            "Starry Eyed",
            "GRAPHIC eyeliner",
            "rainbow dream",
            "Spring 2",
            "Daily makeup with strong red lips",
            "monte carlo",
            "Extreme Sparkle",
            "Soft Sparkle",
            "Classic - because you like it",
            "Summer",
            "swiatecznie",
            "Flormar",
            "multicolor",
            "Snake",
            "Illamasqua Theatre of Nameless",
            "turquoise lace",
            "Natural Everyday eye",
            "The Duchess in this Fairy Tale is a Drama Queen (MUG)",
            "Purple &#038",
            "Heart Breaker :)",
            "galaxy lips",
            "Mermaid Lagoon",
            "Colorful",
            "Sleek",
            "@#$%! the paparazzi",
            "Yellow Mouth",
            "makeup",
            "Purple smoky with glitter liner",
            "Early Spring",
            "Liquid Gold",
            "Pretty Pigments",
            "Vampire",
            "Mysterious Art nouveau masquerade look / mask",
            "Playing with colours",
            "carnival",
            "Purples from MUG",
            "Military gold",
            "Pink Sunset",
            "Bug inspired",
            "Fabulous violet",
            "Bahama Mama",
            "spring into green",
            "Starry Night",
            "Deep blue sea",
            "Pinkey",
            "Orange Glow",
            "Pink accent",
            "Traditional Smokey eye",
            "Deep blue smokey eye",
            "glam *shine*",
            "Classic Look with MUG",
            "Enchanted",
            "Sparkle",
            "Skeleton/Skull",
            "Vegas Lights",
            "Enchanted eyes",
            "Burlesque",
            "Sunny",
            "Like Insomnia",
            "Vegas Lights",
            "Pocahontas",
            "Blue Sky",
            "gold mine",
            "Yellow&#038",
            "Pop of Razzleberry",
            "vegas &#038",
            "Mysterious Queen",
            "Bush Blueberries",
            "Wet Flower",
            "Purple Silver",
            "Rafaello MakeUp Look",
            "Blue with Gold and Green accents",
            "Heartbreaker",
            "Endlessly",
            "Queen of Hearts",
            "lighter look",
            "Peacock",
            "Blue Sparkly Flower :)",
            "Candy",
            "a lot of these things",
            "Ocean Make Up",
            "Black Wings",
            "Expectations",
            "Gold",
            "Daily Bronze",
            "Ferrero Rocher MakeUp Look",
            "Purple Lilac MakeUp Look",
            "Marine eye - polish lake inspiration",
            "Blue and purple",
            "Butterfly",
            "Soft brown",
            "Spring Fling Romantic Eye Makeup",
            "Naked Strangers",
            "Chaos",
            "Under the sea",
            "Pink&#038",
            "Cat Eye Halloween Makeup Look",
            "Back to school",
            "Casual With MUG",
            "Gryffindor",
            "Shop Mac Cook Mac Collection Look",
            "Berry trio",
            "Blacklight eye",
            "violet",
            "Halloween Look - Ring Master",
            "juicy coctail",
            "Autumn Blossoms",
            "Feel like a star.",
            "orange and blue",
            "Everyday Look",
            "Autumn makeup / Boho",
            "Supernatural",
            "Pink Pong",
            "Electric Purple",
            "Orange Trend",
            "Sugar Doll",
            "Purple Romance for a day",
            "Summer Lagoon",
            "New Year's blue",
            "Insomnia Eyes",
            "Seductive Redness",
            "Gray &#038",
            "Blue&#038",
            "Cyber parrot",
            "Burnt Sienna",
            "golden rose.",
            "blue&#038",
            "Hey Now",
            "Goddess :)",
            "Spring look",
            "Enchanted",
            "Fall leaf",
            "Poison Fruit! :)",
            "Sherwood Forest",
            "Arabian Nights",
            "Glittery Gold :)",
            "explosion of colors",
            "Spring",
            "violet bubble gun",
            "Everyday Sultry Makeup",
            "Golden Goddess",
            "Nauti n' Ice",
            "wedding look(flowers)",
            "Midnight Blue",
            "Retro evening make-up",
            "ocean depth",
            "Katy Perry Golden Eye Holiday Makeup",
            "Pomegranate",
            "Miley Cyrus's from amfAR 2014 makeup",
            "Silver classic",
            "DISCO",
            "Dory from Finding Nemo Inspired",
            "black&#038",
            "Beetle MakeUp",
            "Green",
            "ZOMBIE",
            "Romantic",
            "Daily makeup inspiration from Beyonces Music Video - Countdown",
            "pastels",
            "Thursday red",
            "Autumn&#8230",
            "New Year's splendor",
            "cheetah eyes",
            "Poisonous pink",
            "rose",
            "New Wave meets Arabic",
            "Wonder Woman inspired :D",
            "Out and About",
            "Amethyst",
            "Skittles Taste The Rainbow",
            "Neon",
            "60's Glam",
            "pink sunset",
            "TRON: Legacy",
            "Carnival Lace",
            "Wine rapsody",
            "Purple Passion",
            "Neutral makeup",
            "Glamorous Glow",
            "Time for bronze!",
            "Flame Thrower",
            "Light glitter carnival look",
            "Smokey eye",
            "Dita von Teese",
            "greed",
            "Bollywood",
            "Coral Halo",
            "smoky with pop of colour",
            "Fiolet z ro?em",
            "Orange Glamorous",
            "Little Parrot",
            "cut crease",
            "Green beatle",
            "Barbie",
            "MAC Look: Off the Page/ Cranberry",
            "Will you dare?",
            "Summer rainbow",
            "Spring into Colours",
            "Smokey Mango look",
            "..::: Smokey eyes.. :::..",
            "Power",
            "take a break from the winter blues..",
            "Playing with greens",
            "Smoky by Easter",
            "Oil slick",
            "One of my everyday makeup looks",
            "Blue Smokey Eye",
            "Classy",
            "Plum sparkle",
            "crazy brown",
            "Basic Spring look",
            "Flowers of Spring",
            "Romantic",
            "soft purple &#038",
            "Warm classic",
            "Vegas Lights &#038",
            "Sea Shell",
            "Pornography makeup",
            "ocean",
            "Let's play roulette",
            "smokey mug",
            "Unicorn Ice Queen",
            "Exotic makeup for summer",
            "brazy sleeka :)",
            "romantic rose",
            "Birthday Inspired",
            "Classic Winged Liner",
            "Iggy Azalea's from We Can Survive Makeup",
            "Wedding Look",
            "Fearless",
            "Peacock inspired",
            "Dirty Gold MakeUp Look",
            "Carre Pistache Makeup Look",
            "Yellow Frog MakeUp Look",
            "Smokey Lavande",
            "Poison Ivy",
            "Queen of Hearts :)",
            "Candy Cupcake :)",
            "Smitten Kitten",
            "Bohemian",
            "Crazy green look",
            "blue curacao",
            "venomous spider",
            "Lucky Green Flower",
            "green",
            "Sandwiched cocoa smokey eye",
            "funky green",
            "blurple",
            "Rainbow Heaven :)",
            "Hollywood,Glam Look using Naked Palette (Orginal)",
            "Tigerlily - Creative Creased Look",
            "Sugar Skull",
            "chocolate",
            "Purple blue & gold",
            "Glamour Chic",
            "russet feather",
            "Blue Iris Look",
            "Gold Mermaid",
            "Coachella Glam",
            "Insomnia on Mars",
            "Harlequin",
            "Bitten with additives",
            "Purple Smokey",
            "Gold smokey.",
            "Miss Insomnia",
            "Shimmermint",
            "The first touch of fall",
            "Purple Smoke",
            "old gold in a purple ash",
            "Fire and Water",
            "Turquoise",
            ":)",
            "Baby Blue",
            "wedding day",
            "Orange and maroon",
            "Victoria Beckham/Reverse Smoky Eyes",
            "Seductive",
            "Everyday Bronze",
            "Smoky Eyes",
            "Castle",
            "Berry Tones",
            "Electric Blue",
            "no name",
            "Gentle",
            "Blue Chocolate",
            "Bird",
            "Natural with Blue",
            "Sparkling",
            "Blue Smokey Eyes",
            "Kim Kardashian Inspired Eyes",
            "Dark fairy",
            "Rockeresque",
            "Bright Eyed &#038",
            "Electric combination",
            "Summer Party Look",
            "..::Sensuality::..",
            "plum plum",
            "Something blue",
            "Euro 2012 - Poland",
            "The Hulk inspired :)",
            "Berries n Cherries",
            "zebra",
            "Chilli Aztec",
            "Sugar Overdose",
            "Orange and Red <3",
            "Burlesque",
            "Not all glitters is gold!",
            "Sandwich",
            "It's MY Party (Aromaleigh)",
            "Summer Lovin",
            "Burning Phoenix",
            "Dramatic wing",
            "Classic Christmas",
            "Glitter pink",
            "Darkness",
            "Which Side Of The Force Are You?",
            "Green lagoon",
            "Untitled_15",
            "Duochrome cut crease",
            "Golden eye",
            "Baby Blue Sky!",
            "SUMMER",
            "Golden Storm Cloud",
            "Champagne showers",
            "burgundy",
            "Autumn Sunset , studded eyeliner",
            "Your gold",
            "Autumn in Vegas",
            "Mint &#038",
            "Halloween Look - Tinkerbell",
            "Golden cat eye",
            "Graphic Eyeliner Makeup Look",
            "Little Blue",
            "Neon Yellow :)",
            "brown days",
            "Colorful Bollywood",
            "Afterglow &#038",
            "Cobalt in old gold",
            "Gold and Orange",
            "CANDY!",
            "Wild!",
            "Green drama",
            "Graphic MakeUp Look",
            "Yellow&#038",
            "Turquoise Cat",
            "Dramatic Cut Crease",
            "Soft Burgundy Orange MakeUp Look",
            "Fairy Tale",
            "Daydream Summer",
            "Winter is coming",
            "Black Cherry",
            "Rainbow",
            "Grey and browns with the Naked palette",
            "Touch of gold",
            "Red Wine",
            "Tropical psychosis",
            "Roses are&#8230",
            "Sigma Paris",
            "waiting 4 the sunrise",
            "Reddish Bronze :)",
            "Color Burst / Spring, Summer 2012 trends inspired",
            "Soft tangerine",
            "Wicked Game",
            "MUG Summer Sunset",
            "Colorful Spring Makeup",
            "Violet pencil technique",
            "Shimmermint Easter",
            "Candelabra",
            "Jennifer Lopez Oscars 2012 Inspired Eyes",
            "MUG orange pop",
            "Purple and Pink smokey eyes",
            "Blk and Gold",
            "Love Actually",
            "blushing bronze",
            "Purple dream",
            "MAC Look:  Goldmine, Talent Pool, Lucky Green",
            "Rainbow eyes.",
            "wonderful milky way",
            "Mint eyes &marsala lips",
            "Red Wine",
            "New world",
            "Glitter!",
            "Thunder Storm",
            "Lightning",
            "Taupe Eye Makeup",
            "Autumn",
            "True blue",
            "Aquarius",
            "Midsummer nightmare",
            "Rock Chic Makeup",
            "Bronzed stealth",
            "Sensuous Mango",
            "Colorful",
            "Fun colours",
            "Moon",
            "Sunset",
            "innercorner",
            "Black glitter",
            "Sunset",
            "fuuuulcolour",
            "soft pink",
            "Peacock Make up",
            "Inspiration of Autumn",
            "new mats and a new makeup",
            "Caitlin Rose Smoky",
            "Duo chrome prism",
            "It's Fall time",
            "Dark forest",
            "Sunset Ombre",
            "Cut crease with sparklers",
            "Good girl",
            "Give Them Nightmare",
            "Afterglow Lips",
            "juicy color",
            "January Minerals",
            "Cut Crease &#038",
            "Midnight Moondust",
            "light smoky",
            "Makeup Geek's stars",
            "Purple &#038",
            "Sensuous Queen",
            "Kolorow moc",
            "romantic the bride",
            "Liquid Gold",
            "New Year's dark Rainbow",
            "Pixie dust",
            "Holidays makeup",
            "smoky eyes with brown",
            "Classics MakeUp",
            "Chromatic green",
            "Little Glitter",
            "Valentines in Utopia",
            "Blue &#038",
            "Brown Smokey with Colours",
            "deep glossy green",
            "Purple lily",
            "pink dizziness",
            "Emerald Ring MakeUp Look",
            "Powder Pink MakeUp Look",
            "Copper for autumn",
            "Look 4 from Metal Chicks series - Marilyn Manson",
            "gold &#038",
            "Spring colors",
            "Neon Yellow on The Blue Azure",
            "Black gothic smoky with cranberry",
            "Black and blue",
            "Glittery peacock",
            "Sunflower MakeUp Look",
            "Ursula",
            "Summer Sunset",
            "Phoenix",
            "Copper Sparkle",
            "Autumn leaves",
            "Pomegranate",
            "Pink and blue look",
            "Colourful",
            "Retro pinup",
            "Spring Carnival :)",
            "MAC and NYX Look: Purple and Green",
            "MAC Look: Freshwater/Parrot/Sea and Sky",
            "Dramatic Date Night",
            "Peacock wink!",
            "Golden Evening",
            "Blue and silver party look",
            "Fall Makeup",
            "Pink",
            "Natural Golden Eyemakeup",
            "Autumn makeup",
            "SWEET CARMEL",
            "Pop Art Comic Book",
            "Little love story vol. 2",
            "Dark smoky",
            "Smoky1",
            "Blue",
            "Bronze",
            "Forest Story",
            "Gold &#038",
            "New Year's Eve",
            "Midnight Blue",
            "#Longlashes",
            "Smokey Eyes",
            "Soft Glam",
            "Bridal make up",
            "Peacock Eye",
            "gray",
            "Romantic Look",
            "rockstar look",
            "Colorful Christina Aguilera's makeup",
            "Moondust",
            "Plum smokey",
            "Midnight",
            "rainbow",
            "Rose Gold",
            "Colorful Dream",
            "fantasy purple",
            "Keeps gettin' better",
            "Dragon",
            "Amethyst",
            "Make-up Katy Pery - Dark Horse nr.1",
            "romance",
            "Cut Brown",
            "To Brave",
            "Royal Blue **",
            "soft smoky",
            "I need summer",
            "Simple &#038",
            "stage",
            "Let's go to the pool!",
            "Antique Rose",
            "Electric Blue",
            "Inspired by bossassmakeup",
            "*",
            "slightly",
            "New Year Makeup",
            "gold glam",
            "pink diamond",
            "Fire Flame Ombre Liner",
            "Tropic",
            "Maleficent",
            "Summer date",
            "Rock Valentines",
            "Glittery Cut Crease",
            "Morning Fog",
            "In the spotlight with Neptun",
            "Blue Moon",
            "Chickadee",
            "Neon Spring",
            "Blue glitter",
            "Amethystine vision",
            "peacock",
            "Bewitched",
            "Daily make-up!",
            "spring is coming",
            "Feather makeup",
            "Green SMOKE",
            "prom",
            "Pink &#038",
            "wiosna",
            "Green for Christmas",
            "Candy",
            "Golden sapphire",
            "I'm like a peacock",
            "!@#$%^",
            "Holiday look",
            "!@#$%^&#038",
            "!@#$%^&#038",
            "!@#$%^&#038",
            "Once again im green",
            "Pink&#038",
            "Mint MakeUp Look",
            "Pomegranate",
            "Ditta von Teese inspired",
            "Gold line",
            "Purple, Peach &#038; Navy Blue",
            "tropical relax",
            "Pretty in Pink",
            "Fresh look",
            "Parrot",
            "Tie Dyed",
            "Blue Flame",
            "Colorful",
            "In flames",
            "Beyonce B'Day inspired",
            "!@#$%^&#038",
            "Green and Plum Smokey Eye - Two ways to wear Insomnia Pigment",
            "Copper Lights",
            "dark with a golden line",
            "neon pink",
            "Bitten Berry",
            "Purple for a date",
            "Love affair",
            "Cleopatra",
            "Pink",
            "Golden Prom",
            "purple",
            "Rainbow vol.2",
            "Peek a boo Blue",
            "Eggplant with orange",
            "Violet in love",
            "Night Sky",
            "Mermaid",
            "drama queen",
            "Broken heart dramatic Valentine's day , makeup tutorial",
            "Fall into Fall",
            "Foxy matte",
            "60s makeup with a modern twist , tutorial",
            "Ocean Blue",
            "Supermodel",
            "Sunset over Morocco",
            "Summer Twist",
            "Blue & Green cut crease (kind of)",
            "Rainbows and Sunshine :)",
            "Summer Look",
            "Snow white and the huntsman: Evil Queen",
            "simple but pretty",
            "Pixie Dust Love",
            "Galaxy duchess",
            "purple green lantern",
            "my everyday look",
            "Expensive Pink/Wedge/Espresso",
            "Fire and water",
            "Purple and red",
            "Every Day Neutrals",
            "MAC Look: Heatherette Trio 1",
            "MAC Look: Greensmoke/Humid/Espresso",
            "Blue my mind :)",
            "Katniss Everdeen: The Girl On Fire",
            "theMannyMuapalette",
            "Sunset cut crease",
            "Green in the city",
            "Green",
            "Peachless smoky",
            "My daily look!",
            "Retro beauty",
            "Christmas makeup",
            "New Years Eve Makeup",
            "Summer is coming&#8230",
            "dark-nude makeup",
            "Black Smoke",
            "Autumn look!",
            "ice cream paint job",
            "Lucky green retro glam",
            "Neon",
            "MAC Face Chart: Kraft",
            "Makeup Geek Paradise!",
            "Mojito Inspired",
            "Sugarpill Sin ?",
            "Sugar Skull",
            "Metallic Red and black",
            "Neutral Halo Smokey Eye",
            "Power of cobalt",
            "Teal Halo Smokey Eye",
            "Stardust",
            "Think Pink",
            "galaxy",
            "Greenway",
            "Steampunk",
            "Flames",
            "Colorful Cocktail",
            "Teal &#038",
            "Natural Glam",
            "Teal Smokey Eye",
            "Makeup Geek colorful foiled eyeshadows",
            "Charmed Masquerade",
            "Peacock",
            "spring eyes",
            "A Perfect Day Dream",
            "Cut crease like me",
            "Colorfull",
            "Color depth",
            "Purple Passion",
            "Evening eye",
            "vegas lights",
            "Peacock",
            "Last Green Leaf",
            "Sophisticated Turquoise",
            "Vegas&#038",
            "Violet glamour",
            "Daily colorful makeup",
            "autumn",
            "Prince Charming",
            "shimmermint",
            "Copper",
            "Yellow Brick Road",
            "Mercury",
            "sweet pink",
            "date night",
            "beach sunset",
            "Twilight",
            "Purple Haze",
            "Blue Sky",
            "Purple fantasy",
            "Maleficent my makeup",
            "Emerald Glow",
            "Beyonce Mrs. Carter Show Inspired",
            "Rainbow",
            "Parrot",
            "One Night in Utopia",
            "Waiting for Adele",
            "makeup day",
            "Color Play",
            "Show Me Your Lilac",
            "blue",
            "Beautiful Bride",
            "Pink pleasure",
            "Pink Passion",
            "Golden Brown",
            "Golden Glow",
            "Smoking Duchess",
            "MAC Face Chart: One the Scene",
            "MAC Look: Goldmine/Woodwinked/Carbon",
            "juicy grass",
            "MAC Look: Wedding Makeup",
            "60's Inspired Summer Look",
            "Raspberry Shine",
            "Warm Smokey eye",
            "MAC pigment look from Kelly",
            "Evening look",
            "Holiday Bombshell",
            "Summer Sherbet",
            "graphic",
            "Violet",
            "christmas glam",
            "Delicately",
            "Bronze Fall Makeup",
            "Deep forest",
            "Purple look",
            "Wearable Colour",
            "The bling",
            "Purple eyes",
            "artistic",
            "Glitter Liner",
            "Warm Glow",
            "Not classic smoky",
            "Welcome Spring",
            "Thin line",
            "foiled green",
            "purple eyes",
            "Warm browns",
            "ENVY",
            "Beyonce's from Mine video makeup",
            "Exotic Sunset",
            "OCEAN BREEZE",
            "Neon Makeup",
            "Pipeline",
            "Poison Ivy",
            "Only Mystic",
            "Circus",
            "Maleficent",
            "witch makeup",
            "Glamour makeup",
            "Last Dance",
            "Valentine Sweet Valentine",
            "SPRING COLOR",
            "Fantasy Swirl",
            "Aurora",
            "Lady",
            "Blue Line",
            "Early Spring",
            "blue :)",
            "burlesque",
            "Arabic eye",
            "The Black Swan",
            "Kat Von D inspired",
            "Neutral lime",
            "Sugar Rainbow",
            "The Pink",
            "Rose",
            "The Blonds Spring-Summer inspired makeup",
            "Neutral Cut Crease",
            "Pop of color.",
            "Ombre Sping",
            "Peacock with UD Book of Shadows III",
            "MAC Face Chart: Temperature Rising",
            "Flirty Purple",
            "My Little Pony",
            "Gradient Cat Eye",
            "Glamorous party look",
            "Vibrant Purple Halo Smokey Eye",
            "Pop of color",
            "chocolate with orange",
            "Feel the brightness",
            "Warm Glittery Eyes",
            "On the Red Carpet",
            "retro glam",
            "spring look/folied attac",
            "Golden Rose",
            "Silver Halo Smokey Eye",
            "One two three",
            "Burgundy and Teal Halo Eye",
            "Masquerade accent",
            "Casino&#038",
            "Nightlife",
            "Copper Glam",
            "Autumn inspiration",
            "green and blue",
            "Shima~tini",
            "Last Dance",
            "Insomnia with Date Night",
            "holiday party",
            "Batalash inspired",
            "Gold &#038",
            "Nightlife in Vegas",
            "Fantasia",
            "Devilish red",
            "Touch of Purple",
            "wedding  eye",
            "Evening Summer Makeup",
            "moonlight shadow",
            "Ombre violet",
            "sexy look",
            "Twilight Rose",
            "princess wedding makeup",
            "For a Special Day",
            "Liquid Gold",
            "Lavender sea",
            "Egyptian Earth",
            "Date night",
            "gold line",
            "makeup by J.Lo",
            "smoky glitter",
            "Persian",
            "ocean breeze",
            "Faded wing",
            "My easter makeup",
            "Hint of Purple",
            "Tan",
            "Seduction",
            "Autumn",
            "Wispy Romance",
            "Green pop eyes",
            "pretty",
            "Lollipop",
            "MUG Mermaid :)",
            "Fairy",
            "Springtime Skipper/Moonflower/Bateau",
            "Peacock Liner",
            "Sunset flames",
            "Galaxy Dreams",
            "Mermaid!",
            "Purple accent",
            "Olive",
            "New Year eve with Utopia",
            "larus",
            "colorful cut crease",
            "purple &#038",
            "Smoky Garden",
            "Kat von D inspired",
            "Galaxy Inspired Makeup",
            "Blue Lagoon make up",
            "Warm Halo Eye",
            "Enchanted with duochrome",
            "Blueberries in the Forest",
            "Jackpot bling",
            "Sunset",
            "End of the Summer",
            "Autumn Eye",
            "Carnival",
            "Cat Eye",
            "Illuminated Copper",
            "Christmas Glam",
            "Vibrant Peach",
            "Mono Glitter",
            "back to 40's",
            "Cameleon",
            "wedding love",
            "like avatar",
            "purple&#038",
            "electric",
            "Grandma",
            "Fall power",
            "Mundial Inspired",
            "Effloresce",
            "Vegas Lights",
            "Insomniac",
            "May Inspired",
            "Wild Forest",
            "Electric Enchanted",
            "Kim Kardashian look",
            "oriental",
            "Bitten",
            "Rainbow",
            "Tropical Sunset",
            "Gold and pink",
            "Summer Sunset",
            "Daily LOOK",
            "Rusted Wheel",
            "Dragon Wing",
            "light blue",
            "This Week's Most Loved",
            "green pub",
            "Country Girl",
            "When I fell in love with Sugarpill&#8230",
            "The Name's Rango",
            "Broown",
            "Give me some sunshine",
            "red smokey mug",
            "Black Diamond",
            "4th of July!",
            "Fuschia Sunshine",
            "Poison dart soda",
            "mint chip",
            "Cat Liner",
            "Disco",
            "Psycho doll makeup",
            "Green Ransom",
            "Blue Eyes",
            "Dramatic black & pink",
            "Lollipop Candy",
            "Mad as a Hatter",
            "Blue Sea",
            "Classy smokey",
            "Warm Sultry Smokey Eye",
            "plum eye with a pop of color",
            "RAINY DAY",
            "Marlenaﾒs Manny Palette Look",
            "Brown and Copper Halo Smokey Eye",
            "Neon ombre eyeliner",
            "Forest green Smokey eye",
            "Geeks light year",
            "Phantom",
            "Ocean Blue",
            "naturly",
            "Insomniac Lips for Haloween",
            "fall glam",
            "Glitter green",
            "Contrast cut crease",
            "Untitled_10",
            "nude attitude",
            "Moody Plum Halo",
            "Night look!",
            "Soft Mango Tango",
            "Warm Toned EOTD",
            "insomnia",
            "Women's Day",
            "Spring is coming",
            "yellow dream",
            "Wedding matt look",
            "Duochrome smoky",
            "Cut Crease"
    };
}
